name: Build and Deploy Backend

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name:
        run: echo "Building and deploying backend..."

      - name: Set lowercase repository name
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build container image
        run: docker build -f ./backend/Dockerfile -t ghcr.io/${{ env.REPO }}/backend:${{ github.sha }} .

      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/${{ env.REPO }}/backend:${{ github.sha }}

      - name: Deploy to Rahti
        run: |
          oc login --token=${{ secrets.RAHTI_TOKEN }} --server=${{ secrets.RAHTI_SERVER }}
          oc set image deployment/backend backend=ghcr.io/${{ env.REPO }}/backend:${{ github.sha }}
